In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.linear_model import LogisticRegression
df=pd.read_csv('C:/Users/Specter/Desktop/resources/Data Files/2. ST Academy - Classification models resource files/House-Price.csv',header =0)
uv=np.percentile(df.n_hot_rooms,[99])[0]
lv=np.percentile(df.rainfall,[1])[0]
df.rainfall[(df.rainfall < .3*lv )]= .3*lv
df.n_hos_beds=df.n_hos_beds.fillna(df.n_hos_beds.mean())
df['avg_dist'] = (df.dist1+df.dist2+df.dist3+df.dist4)/4
del df['dist1']
del df['dist2']
del df['dist3']
del df['dist4']
del df['bus_ter']
df=pd.get_dummies(df)
del df['airport_NO']
del df['waterbody_None']
df.corr()
del df['parks']
X = df.loc[:, df.columns != 'Sold']
y = df['Sold']
clf_lr = LogisticRegression()
clf_lr.fit(X,y)
import statsmodels.api as sn
X_cons = sn.add_constant(X)
X_cons.head()
import statsmodels.discrete.discrete_model as sm
logit = sm.Logit(y, X_cons).fit()
logit.summary()

<ipython-input-1-118fafcfe37b>:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rainfall[(df.rainfall < .3*lv )]= .3*lv
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Optimization terminated successfully.
         Current function value: 0.557633
         Iterations 7


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                   Sold   No. Observations:                  506
Model:                          Logit   Df Residuals:                      490
Method:                           MLE   Df Model:                           15
Date:                Fri, 23 Apr 2021   Pseudo R-squ.:                  0.1907
Time:                        06:20:49   Log-Likelihood:                -282.16
converged:                       True   LL-Null:                       -348.64
Covariance Type:            nonrobust   LLR p-value:                 5.608e-21
============================================================================================
                               coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------
const                       -2.0162      2.649     -0.761      0.447      -7.209       3.176
price                       -0.2732      0.033     -8.294      0.000      -0.338      -0.209
resid_area                   0.0209      0.027      0.787      0.431      -0.031       0.073
air_qual                    -5.0600      1.817     -2.785      0.005      -8.621      -1.499
room_num                     1.1026      0.276      3.989      0.000       0.561       1.644
age                         -0.0019      0.007     -0.283      0.777      -0.015       0.011
teachers                     0.3133      0.064      4.904      0.000       0.188       0.438
poor_prop                   -0.2070      0.034     -6.129      0.000      -0.273      -0.141
n_hos_beds                   0.1705      0.071      2.398      0.016       0.031       0.310
n_hot_rooms                 -0.0613      0.054     -1.132      0.258      -0.167       0.045
rainfall                    -0.0039      0.008     -0.463      0.643      -0.020       0.012
avg_dist                    -0.4011      0.097     -4.117      0.000      -0.592      -0.210
airport_YES                 -0.1411      0.210     -0.672      0.502      -0.553       0.270
waterbody_Lake              -0.1034      0.304     -0.340      0.734      -0.699       0.492
waterbody_Lake and River    -0.0628      0.327     -0.192      0.848      -0.704       0.579
waterbody_River              0.2321      0.255      0.911      0.362      -0.267       0.731
============================================================================================
"""

In [2]:
clf_lr.predict_proba(X)

array([[1.24742967e-01, 8.75257033e-01],
       [3.74418697e-01, 6.25581303e-01],
       [9.99771811e-01, 2.28188641e-04],
       ...,
       [2.71538465e-01, 7.28461535e-01],
       [2.77806563e-01, 7.22193437e-01],
       [1.71123211e-01, 8.28876789e-01]])

In [7]:
#Default boundary condition is 0.5
y_pred = clf_lr.predict(X)
y_pred

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,

In [6]:
# Set the Custom boundary
y_pred_03 = (clf_lr.predict_proba(X)[:,1] >= 0.3)

In [8]:
y_pred_03

array([ True,  True, False,  True, False, False,  True, False, False,
        True,  True,  True, False,  True,  True,  True,  True, False,
        True,  True, False,  True, False, False,  True,  True,  True,
        True,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False, False,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True, False,  True,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
        True,  True,  True,  True,  True,  True, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False,  True,
       False, False,

In [9]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y, y_pred)

array([[197,  79],
       [ 78, 152]], dtype=int64)

In [10]:
 confusion_matrix(y, y_pred_03)

array([[119, 157],
       [ 17, 213]], dtype=int64)