In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
df=pd.read_csv('C:/Users/Specter/Desktop/resources/Data Files/2. ST Academy - Classification models resource files/House-Price.csv',header =0)
uv=np.percentile(df.n_hot_rooms,[99])[0]
lv=np.percentile(df.rainfall,[1])[0]
df.rainfall[(df.rainfall < .3*lv )]= .3*lv
df.n_hos_beds=df.n_hos_beds.fillna(df.n_hos_beds.mean())
df['avg_dist'] = (df.dist1+df.dist2+df.dist3+df.dist4)/4
del df['dist1']
del df['dist2']
del df['dist3']
del df['dist4']
del df['bus_ter']
df=pd.get_dummies(df)
del df['airport_NO']
del df['waterbody_None']
del df['parks']
import statsmodels.api as sn
from sklearn.linear_model import LinearRegression
X_multi = df.drop('price',axis = 1)
y_multi = df['price']
X_multi_cons = sn.add_constant(X_multi)
lm_multi = sn.OLS(y_multi, X_multi_cons).fit()
lm3 = LinearRegression()
lm3.fit(X_multi,y_multi)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_multi,y_multi, test_size = .2, random_state = 0)
lm_a = LinearRegression()
lm_a.fit(X_train,y_train)
y_test_a = lm_a.predict(X_test) #predicted
y_train_a = lm_a.predict(X_train)
from sklearn.metrics import r2_score
r2_score(y_test, y_test_a) #Use this to evaluate the performance of the model

<ipython-input-3-783364ecbd3a>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rainfall[(df.rainfall < .3*lv )]= .3*lv


0.6398328264530885

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
df=pd.read_csv('C:/Users/Specter/Desktop/resources/Data Files/2. ST Academy - Classification models resource files/House-Price.csv',header =0)
uv=np.percentile(df.n_hot_rooms,[99])[0]
lv=np.percentile(df.rainfall,[1])[0]
df.rainfall[(df.rainfall < .3*lv )]= .3*lv
df.n_hos_beds=df.n_hos_beds.fillna(df.n_hos_beds.mean())
df['avg_dist'] = (df.dist1+df.dist2+df.dist3+df.dist4)/4
del df['dist1']
del df['dist2']
del df['dist3']
del df['dist4']
del df['bus_ter']
df=pd.get_dummies(df)
del df['airport_NO']
del df['waterbody_None']
del df['parks']
import statsmodels.api as sn
from sklearn.linear_model import LinearRegression
X_multi = df.drop('Sold',axis = 1)
y_multi = df['Sold']
X_multi_cons = sn.add_constant(X_multi)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_multi,y_multi, test_size = .2, random_state = 0)
lm_a = LinearRegression()
lm_a.fit(X_train,y_train)
y_test_a = lm_a.predict(X_test) #predicted
y_train_a = lm_a.predict(X_train)
from sklearn.metrics import r2_score
from sklearn import preprocessing
scalar = preprocessing.StandardScaler().fit(X_train)
X_train_s = scalar.transform(X_train)
X_test_s = scalar.transform(X_test)
from sklearn.linear_model import Ridge
lm_r = Ridge(alpha = 0.5)
lm_r.fit(X_train_s, y_train)
r2_score(y_test, lm_r.predict(X_test_s))
from sklearn.model_selection import validation_curve
param_range = np.logspace(-2,8,100)
train_scores, test_scores = validation_curve(Ridge(), X_train_s, y_train, 'alpha', param_range, scoring= 'r2' )
train_mean = np.mean(train_scores, axis =1)
test_mean = np.mean(test_scores, axis =1)
np.where(test_mean==max(test_mean))

<ipython-input-1-4cc4c5352d8a>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rainfall[(df.rainfall < .3*lv )]= .3*lv
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:67: FutureWarning: Pass param_name=alpha, param_range=[1.00000000e-02 1.26185688e-02 1.59228279e-02 2.00923300e-02
 2.53536449e-02 3.19926714e-02 4.03701726e-02 5.09413801e-02
 6.42807312e-02 8.11130831e-02 1.02353102e-01 1.29154967e-01
 1.62975083e-01 2.05651231e-01 2.59502421e-01 3.27454916e-01
 4.13201240e-01 5.21400829e-01 6.57933225e-01 8.30217568e-01
 1.04761575e+00 1.32194115e+00 1.66810054e+00 2.10490414e+00
 2.65608778e+00 3.35160265e+00 4.22924287e+00 5.33669923e+00
 6.73415066e+00 8.49753436e+00 1.07226722e+01 1.35304777e+01
 1.70735265e+01 2.15443469e+01 2.71858824e+01 3.43046929e+01
 4.32876128e+01 

(array([25], dtype=int64),)

In [2]:
lm_r_best = Ridge(alpha=param_range[28])
lm_r_best.fit(X_train_s,y_train)
r2_score(y_test, lm_r_best.predict(X_test_s))
r2_score(y_train, lm_r_best.predict(X_train_s))

0.21045948618137766

In [3]:
from sklearn.neighbors import KNeighborsClassifier
clf_knn_1 = KNeighborsClassifier(n_neighbors=1)

In [4]:
clf_knn_1.fit(X_train_s , y_train)

KNeighborsClassifier(n_neighbors=1)

In [5]:
from sklearn.metrics import confusion_matrix


In [6]:
confusion_matrix(y_test, clf_knn_1.predict(X_test_s))

array([[31, 27],
       [24, 20]], dtype=int64)

In [16]:
accuracy_score?


Object `accuracy_score` not found.


In [7]:

from sklearn.metrics import precision_score, recall_score, accuracy_score

In [8]:
accuracy_score(y_test, clf_knn_1.predict(X_test_s))

0.5

In [9]:
clf_knn_3 = KNeighborsClassifier(n_neighbors=3)
clf_knn_3.fit(X_train_s, y_train)
accuracy_score(y_test,clf_knn_3.predict(X_test_s))

0.5098039215686274

In [11]:
#Single model for multiple values of K
from sklearn.model_selection import GridSearchCV

In [25]:
params = {'n_neighbors':range(1,101)}

In [26]:
params

{'n_neighbors': range(1, 101)}

In [27]:
grid_search_cv = GridSearchCV(KNeighborsClassifier(), params)

In [28]:
grid_search_cv.fit(X_train_s, y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': range(1, 101)})

In [29]:
grid_search_cv.best_params_

{'n_neighbors': 12}

In [30]:
optimised_KNN = grid_search_cv.best_estimator_

In [31]:
y_test_pred = optimised_KNN.predict(X_test_s)

In [32]:
confusion_matrix(y_test, y_test_pred)

array([[40, 18],
       [25, 19]], dtype=int64)

In [33]:
accuracy_score(y_test, y_test_pred)

0.5784313725490197